name: 'Deploy package documentation'
description: 'Build and deploy the documentation for a Julia package.'
author: 'David Anthoff'
runs:
  using: 'node12'
  main: 'lib/main.js'
  wait: 'lib/wait.js'
